services:
  rust:
    container_name: rust
    build: ./
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    container_name: postgres
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGREs_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 60s
      retries: 10
